### ISSUE TITLE
image path with directories interpreted as recipe or route

### ISSUE THREAD

**Issue by jimlambie** [dadi/cdn#184]
for example:

`/samples/test.jpg` -> is resolved as URL format v1, recipe name "samples"

@eduardoboucas would appreciate your views on this one. I have a solution, but you won't like it...

**Comment by jimlambie** [comment]
This is the line causing trouble 
https://github.com/dadi/cdn/blob/master/dadi/lib/handlers/factory.js#L52

A path with directories in it will always be identified as v1 and then the request subsequently fails because the directory isn't going to resolve to a recipe or route name.

A possible solution is to force recipes and routes to start with a special character, e.g. _thumbnail

**Comment by eduardoboucas** [comment]
If I understand correctly, the issue is that `/jpg/80(...)` (v1) can't be distinguished from `/samples/test.jpg` (v2). If that's the case, could we make the logic that detects the version a bit more elaborate and assume v1 only if `jpg` matches a valid format?

(Sorry if I'm missing the point entirely!)

**Comment by jimlambie** [comment]
Closed via b9a45e4c939873200ad159d70454e9bb22a0fa0d
