### ISSUE TITLE
Adaptors in repo

### ISSUE THREAD

**Issue by abovedave** [dadi/cdn#232]
I think it would be cool to see a maintained list of front-end adaptors for using *CDN*. We've seen a few people write adaptors such as a Dust.js helper and partial, but if we include them in the repo they are tied to the version so if we make changes, the adaptors are updated.

E.g., a Dust.js partial

```dust.js
{>"partials/img"
    width="850"
    ratio="1-1"
    src="{primaryAsset.image.path}"
    alt="{primaryAsset.image.imageCaption}"
/}
```

Thoughts?

**Comment by jimlambie** [comment]
@abovebored where would these live? In the CDN repo? We need a way to manage these types of resources, as now with multiple template engines we could have partials built in Dust, Pug, ES6 literals... 

Could this be bundled in with the discussion about the plugins/extensions support? https://github.com/dadi/cdn/issues/168

**Comment by eduardoboucas** [comment]
Plugin support: ✅ 

Where should we go with this one now? I personally don't think the CDN repo is the right place for plugins or front-end libraries. I'm thinking the [registry](https://github.com/dadi/registry) is the best place for them.

The repo is already in place, so there's nothing stopping us from adding any resources to it. Unless you guys think otherwise, should we close this one?

**Comment by jimlambie** [comment]
@eduardoboucas  agreed
