### ISSUE TITLE
Change default resizeStyle to aspectfit

### ISSUE THREAD

**Issue by jimlambie** [dadi/cdn#255]
In previous versions of CDN the default `resizeStyle` was "aspectfit" (that is, when no `resize`/`resizeStyle` parameter is supplied).

This no longer seems to be the case:

https://cdn.somedomain.tech/samples/dog.jpeg?w=600&blur=0&resize=aspectfit
https://cdn.somedomain.tech/samples/dog.jpeg?w=600&blur=0

**Comment by eduardoboucas** [comment]
Turns out this isn't an issue. The default `resizeStyle` is and always has been `aspectfill`. But I think this is a good time to discuss the possibility of changing that.

If I have a large original image and I want to display a smaller version (say 600px) to save bandwidth, I would expect this to work:

https://cdn.somedomain.tech/samples/dog.jpeg?w=600

Except this gives me an image with a width of 600px and the height of the original image, effectively cropping the image. I think this is an odd default behaviour. Cropping is a very specific task that should only be performed when asked for specifically – how many times will people be looking for a vertical slice with whatever pixels happen to exist on the leftmost part of the image?

If we make `aspectfit` the default, the above URL would be equivalent to https://cdn.somedomain.tech/samples/dog.jpeg?w=600&resizeStyle=aspectfit and to get the current behaviour (i.e. cropping the image) you'd need to actively specify `resizeStyle=aspectfill` (https://cdn.somedomain.tech/samples/dog.jpeg?w=600&resizeStyle=aspectfill).

This is obviously a breaking change, so let's think if it's worth implementing in the next major.

👋
