### ISSUE TITLE
Invalidate cache on version change

### ISSUE THREAD

**Issue by mingard** [dadi/cdn#280]
If the module version is changed, it would be useful to invalidate the entire cache.

In cases where the output file is expected to differ, it removes the requirement to manually clear the cache before launch.

It also removes the potential to incorrectly diagnose a bug based on a request to a cached result for a previously erroneous asset that should be fixed as part of the update.

**Comment by eduardoboucas** [comment]
Sorry, I misunderstood your suggestion when we discussed it on Slack, as I didn't realise you were referring to the module version.

I agree that in situations where you're upgrading CDN to fix an issue with an image, getting the cache automatically purged for you would be a nice to have. But in my opinion the potential negative side effects of this outweigh the advantages.

Imagine that we release a patch version of CDN to fix an issue that is completely unrelated to image processing (e.g. the engine that handles minification of JS files). When developers do the upgrade, they could see gigabytes of perfectly fine cached images deleted for no reason, and with no way to avoid the process. This would be a bit difficult to explain, and depending on the nature and scale of the infrastructure, it could be a pain.

In this case, I'm much more in favour of making the task of purging the cache as simple as possible for people to perform, rather than make assumptions and perform the task for them. Perhaps we could build a `dadi cdn cache:purge` command into CLI?

**Comment by mingard** [comment]
@eduardoboucas I think it's a bit overkill to have that as part of CLI. You may as well clear the cache directory manually.

**Comment by eduardoboucas** [comment]
> @eduardoboucas I think it's a bit overkill to have that as part of CLI. You may as well clear the cache directory manually.

If you're using disk caching, yes, but a single CLI command would be handy if you're using Redis. In any case, it's totally just a nice to have. I was just trying to meet you in the middle. 🙂

**Comment by jimlambie** [comment]
It's already possible to clear the cache via an HTTP request to the CDN instance. Would that be useful, perchance?

**Comment by mingard** [comment]
@eduardoboucas Redis - now I can see how that would be useful. Would CLI know where to clear?

@jimlambie Is that for a single image or the entire cache?

**Comment by eduardoboucas** [comment]
CDN 3.0 will include a much more comprehensive mechanism for flushing the cache (by domain, filename or URL parameters), so the use case described here would be achieved by issuing a flush command after updating the module version.
